# fly.toml app configuration file generated for shram-sangam on 2025-03-20T15:38:27+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shram-sangam'
primary_region = 'bom'
console_command = '/rails/bin/rails console'

[build]
  release_command = "bundle exec rake db:seed"

[processes]
  app = "bundle exec puma -b tcp://0.0.0.0:3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

